# Generated by Django 3.2.20 on 2023-08-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='harmful_content',
            field=models.CharField(blank=True, choices=[('le', 'Lead'), ('ca', 'Cadmium'), ('me', 'Mercury'), ('so', 'Solvents'), ('mm', 'Methyl Methacrylate'), ('ar', 'Aromatic Hydrocarbons')], max_length=2, null=True),
        ),
    ]
