# Generated by Django 3.2.20 on 2023-08-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_material_harmful_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_category',
            field=models.CharField(blank=True, choices=[('oi', 'Oil Paint'), ('ac', 'Acrylic Paint'), ('wa', 'Watercolour Paint'), ('in', 'Ink Paint'), ('br', 'Brush'), ('pe', 'Pencil'), ('ca', 'Canvas'), ('pa', 'Paper')], max_length=2, null=True),
        ),
    ]
